### ISSUE TITLE
请问大佬，又报错了，昨天还好的。

### ISSUE THREAD

**Issue by ghsssss** [397179459/iMaoTai-reserve#3]
08/21/2023 09:30:14 AM  privateCrypt.py : ERROR  !!!!请配置config.py中PRIVATE_AES_KEY(AES的私钥)
Traceback (most recent call last):
  File "/ql/data/scripts/397179459_iMaoTai-reserve_master/main.py", line 33, in <module>
    aes_key = privateCrypt.get_aes_key()
  File "/ql/data/scripts/397179459_iMaoTai-reserve_master/privateCrypt.py", line 13, in get_aes_key
    raise ValueError
ValueError

**Comment by ghsssss** [comment]
@397179459

**Comment by ghsssss** [comment]
PRIVATE_AES_KEY是高德地图的key吗

**Comment by 397179459** [comment]
@ghsssss 看一下最新的config.py，里面有说明

**Comment by ghsssss** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/configparser.py", line 791, in get
    value = d[option]
  File "/usr/local/lib/python3.10/collections/__init__.py", line 986, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/local/lib/python3.10/collections/__init__.py", line 978, in __missing__
    raise KeyError(key)
KeyError: 'enddate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/data/scripts/397179459_iMaoTai-reserve_master/main.py", line 39, in <module>
    if (configs.get(section, 'enddate') != 9) and (TODAY > configs.get(section, 'enddate')):
  File "/usr/local/lib/python3.10/configparser.py", line 794, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'enddate' in section:

**Comment by ghsssss** [comment]
我已经添加高德地图的key @397179459

**Comment by 397179459** [comment]
![image](https://github.com/397179459/iMaoTai-reserve/assets/44400790/fc9c53f1-078f-4500-bd0d-6e841906556c)

你没有自己配置过login.py吧，你配置的时候就要选择这个 @ghsssss

**Comment by ghsssss** [comment]
文档有点问题，c'redentials不能删除，删除报错，其他按流程走没啥问题

**Comment by ghsssss** [comment]
只能清空，不能删除，代码那里会导致过不去

**Comment by ghsssss** [comment]
而且高德key必须事情web服务类型，不能选web类型。。建议标注一下

**Comment by 397179459** [comment]
> 只能清空，不能删除，代码那里会导致过不去

删除文件后，不能直接运行main.py，运行login.py会报错吗？可以展示下报错，我之前测过了，会自动创建的。


> 而且高德key必须事情web服务类型，不能选web类型。。建议标注一下
这个我当时没注意，就是从网上找的注册方法。

**Comment by ghsssss** [comment]
Traceback (most recent call last):
  File "/Users/hula9hao/Downloads/iMaoTai-reserve-master/login.py", line 23, in <module>
    path = get_credentials_path()
  File "/Users/hula9hao/Downloads/iMaoTai-reserve-master/login.py", line 19, in get_credentials_path
    os.mkdir(os.path.join(home_path, 'myConfig'))
FileExistsError: [Errno 17] File exists: '/Users/hula9hao/Downloads/iMaoTai-reserve-master/myConfig'

**Comment by 397179459** [comment]
> Traceback (most recent call last): File "/Users/hula9hao/Downloads/iMaoTai-reserve-master/login.py", line 23, in path = get_credentials_path() File "/Users/hula9hao/Downloads/iMaoTai-reserve-master/login.py", line 19, in get_credentials_path os.mkdir(os.path.join(home_path, 'myConfig')) FileExistsError: [Errno 17] File exists: '/Users/hula9hao/Downloads/iMaoTai-reserve-master/myConfig'

更新一下代码，再试试

**Comment by ghsssss** [comment]
可以了。

**Comment by ghsssss** [comment]
https://console.amap.com/dev/key/app
创建新应用-添加key-Web服务 大致流程 @397179459
